=== Henrique060/IECD/bin/XSLT.demo/7 - proprietarios_veiculos/proprietarios.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Validação da lista de proprietários de veículos -->
<!-- Porfírio Filipe -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="utilType.xsd"/>
	<xs:simpleType name="carType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Audi, A4, Ligeiro"/>
			<xs:enumeration value="VW, Golf, Ligeiro"/>
			<xs:enumeration value="Seat, Toledo, Ligeiro"/>
			<xs:enumeration value="Seat, Ibiza, Ligeiro"/>
			<xs:enumeration value="Honda, CBR 1000, Motociclo"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AT_Matrícula">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{2}-[0-9]{2}-[0-9]{2}|[0-9]{2}-[A-Z]{2}-[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Próprio" type="AT_Nome"/>
	<xs:element name="Apelido" type="AT_Nome"/>
	<xs:element name="LPROPRIETÁRIOS">
		<xs:annotation>
			<xs:documentation>Lista de Proprietários</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PROPRIETÁRIO" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="NOME">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element ref="Próprio" maxOccurs="unbounded"/>
										<xs:element ref="Apelido" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="CONTACTO">
								<xs:annotation>
									<xs:documentation>Contatos</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:choice>
										<xs:element name="EMAIL" type="AT_emailAddress" minOccurs="1" maxOccurs="1"/>
										<xs:element name="TELEFONE" type="AT_Telefone" minOccurs="1" maxOccurs="1"/>
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element name="VEÍCULO" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Veiculos</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="MATRÍCULA" use="required">
										<xs:simpleType>
											<xs:restriction base="AT_Matrícula">
												<xs:length value="8"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="TIPO" type="carType" use="required">
										<xs:annotation>
											<xs:documentation>Marca,  Modelo e Categoria</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="DATAINSPEÇÃO" type="AT_Data"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="MORADA" type="xs:normalizedString" use="required"/>
					</xs:complexType>
					<xs:key name="pk_veiculo">
						<xs:selector xpath="VEÍCULO"/>
						<xs:field xpath="@MATRÍCULA"/>
					</xs:key>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="ak_email">
			<xs:selector xpath="./*/CONTACTO"/>
			<xs:field xpath="EMAIL"/>
		</xs:unique>
		<xs:unique name="ak_telefone">
			<xs:selector xpath="./*/CONTACTO"/>
			<xs:field xpath="TELEFONE"/>
		</xs:unique>
	</xs:element>
</xs:schema>

=== Henrique060/IECD/bin/XSLT.demo/7 - proprietarios_veiculos/proprietarios.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- exemplo dtd <!DOCTYPE LPROPRIETÁRIOS SYSTEM "proprietarios.dtd"> -->
<!-- Sample by Porfírio Filipe -->
<?xml-stylesheet type="text/xsl" href="inspec-html.xsl"?>
<LPROPRIETÁRIOS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="proprietarios.xsd">
	<PROPRIETÁRIO MORADA="Travessa Sítio da Cruz Dourada, nº 12, Agualva-Cacém">
		<NOME>
			<Próprio>Aurora</Próprio>
			<Apelido>Áurea</Apelido>
			<Apelido>Salve</Apelido>-<Apelido>Rainha</Apelido>
		</NOME>
		<CONTACTO>
			<TELEFONE>967788999</TELEFONE>
		</CONTACTO>
		<VEÍCULO TIPO="Audi, A4, Ligeiro" MATRÍCULA="AB-11-02" DATAINSPEÇÃO="01/08/2021"/>
	</PROPRIETÁRIO>
	<PROPRIETÁRIO MORADA="Av. da Liberdade, nº 10, Lisboa">
		<NOME>
			<Próprio>José</Próprio> Policarpo <Apelido>da Silva</Apelido>
			<Apelido>Corte</Apelido>-<Apelido>Real</Apelido>
		</NOME>
		<CONTACTO>
			<EMAIL>Anao.Jonas@mail.pt</EMAIL>
		</CONTACTO>
		<VEÍCULO TIPO="Honda, CBR 1000, Motociclo" MATRÍCULA="AB-11-00" DATAINSPEÇÃO="01/08/2021"/>
	</PROPRIETÁRIO>
	<PROPRIETÁRIO MORADA="Av. Conselheiro Emidio Navarro, nº 1, Chelas">
		<NOME>
			<Próprio>Anacleto</Próprio>
			<Próprio>João</Próprio>
			<Apelido>Dias</Apelido>
			<Apelido>da Silva</Apelido>
		</NOME>
		<CONTACTO>
			<EMAIL>Anao.Jonas@mail.pt</EMAIL>
		</CONTACTO>
		<VEÍCULO TIPO="Seat, Toledo, Ligeiro" MATRÍCULA="AB-11-01" DATAINSPEÇÃO="03/01/2021"/>
		<VEÍCULO TIPO="Seat, Ibiza, Ligeiro" MATRÍCULA="AB-11-01" DATAINSPEÇÃO="19/12/2021"/>
	</PROPRIETÁRIO>
</LPROPRIETÁRIOS>
