=== Henrique060/IECD/XSLT.demo/2 - bar_cerveja/bc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- by Porfírio Filipe -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="lista_bar_cerveja">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="bar" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="oBar" type="xs:ID" use="required"/>
            <xs:attribute name="nome" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="cerveja" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="aCerveja" type="xs:ID" use="required"/>
            <xs:attribute name="nome" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="bar_cerveja" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="oBar" type="xs:IDREF" use="required"/>
                <xs:attribute name="aCerveja" type="xs:IDREF" use="required"/>
                <xs:attribute name="preço" type="xs:decimal" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="ak_bar">
      <xs:selector xpath="bar"/>
      <xs:field xpath="@nome"/>
    </xs:unique>
    <xs:unique name="ak_cerveja">
      <xs:selector xpath="cerveja"/>
      <xs:field xpath="@nome"/>
    </xs:unique>
    <xs:key name="pk_bar">
      <xs:selector xpath="bar"/>
      <xs:field xpath="@oBar"/>
    </xs:key>
    <xs:key name="pk_cerveja">
      <xs:selector xpath="cerveja"/>
      <xs:field xpath="@aCerveja"/>
    </xs:key>
    <xs:key name="pk_bc">
      <xs:selector xpath="bar_cerveja"/>
      <xs:field xpath="@oBar"/>
      <xs:field xpath="@aCerveja"/>
    </xs:key>
    <xs:keyref name="fk_bar" refer="pk_bar">
      <xs:selector xpath="bar_cerveja"/>
      <xs:field xpath="@oBar"/>
    </xs:keyref>
    <xs:keyref name="fk_cerveja" refer="pk_cerveja">
      <xs:selector xpath="bar_cerveja"/>
      <xs:field xpath="@aCerveja"/>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== Henrique060/IECD/XSLT.demo/2 - bar_cerveja/bc.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!-- by Porfírio Filipe -->
<?xml-stylesheet type="text/xsl" href="lista.xsl"?>
<lista_bar_cerveja xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bc.xsd">
	<!-- Bares -->
  <bar oBar="b1" nome="O Bar Inglês"/>
  <bar oBar="b2" nome="O Pinguim"/>
  <bar oBar="b3" nome="Alfaiataria"/>
  <bar oBar="b4" nome="Quimera"/>
  <bar oBar="b5" nome="Musa"/>
  <bar oBar="b6" nome="Red Frog"/>
  <!-- Cervejas -->
  <cerveja aCerveja="c1" nome="Budweiser"/>
  <cerveja aCerveja="c2" nome="Antarctica"/>
  <cerveja aCerveja="c3" nome="Sagres"/>
  <cerveja aCerveja="c4" nome="Heineken"/>
  <cerveja aCerveja="c5" nome="Amstel"/>
  <cerveja aCerveja="c6" nome="Guinness"/>
  <cerveja aCerveja="c7" nome="Duvel"/>
  <cerveja aCerveja="c8" nome="Sapporo Premium"/>
  <cerveja aCerveja="c9" nome="Baltika 8"/>
  <cerveja aCerveja="c10" nome="Paceña Pico de Oro"/>
  <cerveja aCerveja="c11" nome="Samuel Adams"/>
  <!-- Associação entre bares e cervejas -->
  <bar_cerveja oBar="b1" aCerveja="c2" preço="6.00"/>
  <bar_cerveja oBar="b2" aCerveja="c2" preço="6.50">Boa Escolha! </bar_cerveja>
  <bar_cerveja oBar="b3" aCerveja="c5" preço="5.50">Excelente Escolha! </bar_cerveja>
  <bar_cerveja oBar="b4" aCerveja="c5" preço="5.00">Razoável Escolha! </bar_cerveja>
  <bar_cerveja oBar="b5" aCerveja="c2" preço="6.50">Boa Escolha! </bar_cerveja>
  <bar_cerveja oBar="b6" aCerveja="c3" preço="5.50">Excelente Escolha! </bar_cerveja>
  <bar_cerveja oBar="b3" aCerveja="c4" preço="5.00">Razoável Escolha! </bar_cerveja>
  <bar_cerveja oBar="b3" aCerveja="c3" preço="6.50">Muito Boa Escolha! </bar_cerveja>
  <bar_cerveja oBar="b1" aCerveja="c3" preço="5.50">Excelente Escolha! </bar_cerveja>
  <bar_cerveja oBar="b2" aCerveja="c5" preço="5.00">Razoável Escolha! </bar_cerveja>
  <bar_cerveja oBar="b3" aCerveja="c2" preço="6.50">Má Escolha! </bar_cerveja>
  <bar_cerveja oBar="b4" aCerveja="c3" preço="5.50">Excelente Escolha! </bar_cerveja>
  <bar_cerveja oBar="b5" aCerveja="c5" preço="5.00">Razoável Escolha! </bar_cerveja>
</lista_bar_cerveja>
